"""
Configuration centrale des plateformes et de leurs rapports.
Chaque plateforme déclare ses rapports Excel et PowerPoint.
"""

PLATFORMS = {
    'mobile-dr2': {
        'label':   'Réseau Mobile & DR2',
        'icon':    '📡',
        'color':   '#003087',
        'color2':  '#0047cc',
        'domains': ['mobile', 'dr2'],
        'excel_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'DR2 / Daily Report',
                'desc':     'Tableau de bord quotidien DR2 par région et escalade',
                'url_name': 'dr2_daily',
                'url_kwargs': {},
                'icon':     '📱',
                'badge':    'Excel',
            },
            {
                'num':      2,
                'title':    'Rapport 2',
                'subtitle': 'Synthèse Mensuelle',
                'desc':     'Analyse mensuelle des incidents Mobile et violations DR2',
                'url_name': 'reporting_network',
                'url_kwargs': {'platform': 'mobile-dr2'},
                'icon':     '📊',
                'badge':    'Excel',
            },
            {
                'num':      3,
                'title':    'Rapport 3',
                'subtitle': 'Bases des Incidents',
                'desc':     'Onglets Réseau Mobile + DR2 générés depuis le fichier source',
                'url_name': 'platform_bases_incidents',
                'url_kwargs': {'platform': 'mobile-dr2'},
                'icon':     '📋',
                'badge':    'Excel',
            },
        ],
        'pptx_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Comité GDI',
                'desc':     'Rapport PowerPoint — Gestion des Incidents tous domaines',
                'url_name': 'generate_pptx_platform',
                'url_kwargs': {'platform': 'mobile-dr2'},
                'icon':     '🎯',
                'badge':    'PowerPoint',
            },
        ],
        'import': {
            'domains': ['mobile', 'dr2'],
            'hint':    'Fichier brut ticketing mobile (RESEAU_MOBILE_*.xlsx) ou fichier Bases des Incidents',
            'accept':  '.xlsx,.xls',
        },
    },

    'fixe': {
        'label':   'Réseau Fixe',
        'icon':    '☎️',
        'color':   '#059669',
        'color2':  '#10b981',
        'domains': ['fixe'],
        'tool_reports': [
            {
                'num':      1,
                'title':    'Outil 1',
                'subtitle': 'Rapport Hebdo DCO — FTTH',
                'desc':     'Carte choroplèthe du Togo avec incidents FTTH par région et export PPTX',
                'url_name': 'fixe_rapport_ftth',
                'url_kwargs': {},
                'icon':     '🗺️',
                'badge':    'Interactif',
            },
        ],
        'excel_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Bases des Incidents',
                'desc':     'Onglet Réseau Fixe généré depuis le fichier source ticketing',
                'url_name': 'platform_bases_incidents',
                'url_kwargs': {'platform': 'fixe'},
                'icon':     '📋',
                'badge':    'Excel',
            },
            {
                'num':      2,
                'title':    'Rapport 2',
                'subtitle': 'Synthèse Réseau Fixe',
                'desc':     'Analyse mensuelle des incidents du réseau fixe',
                'url_name': 'reporting_network',
                'url_kwargs': {'platform': 'fixe'},
                'icon':     '📊',
                'badge':    'Excel',
            },
        ],
        'pptx_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Comité GDI — Fixe',
                'desc':     'Section Réseau Fixe du rapport GDI',
                'url_name': 'generate_pptx_platform',
                'url_kwargs': {'platform': 'fixe'},
                'icon':     '🎯',
                'badge':    'PowerPoint',
            },
        ],
        'import': {
            'domains': ['fixe'],
            'hint':    'Fichier brut ticketing réseau fixe',
            'accept':  '.xlsx,.xls',
        },
    },

    'transmission': {
        'label':   'Transport',
        'icon':    '🔗',
        'color':   '#d97706',
        'color2':  '#f59e0b',
        'domains': ['transport'],
        'tool_reports': [
            {
                'num':      1,
                'title':    'Outil 1',
                'subtitle': 'Rapport NOC Transport',
                'desc':     'Génération du rapport hebdomadaire NOC Transport depuis TRANSMISSION_*.xlsx',
                'url_name': 'transport_rapport_noc',
                'url_kwargs': {},
                'icon':     '📋',
                'badge':    'Interactif',
            },
            {
                'num':      2,
                'title':    'Outil 2',
                'subtitle': 'Rapport DCO Liens FO',
                'desc':     'Présentation interactive des coupures fibre optique avec carte et export PPTX',
                'url_name': 'transport_rapport_fo',
                'url_kwargs': {},
                'icon':     '🗺️',
                'badge':    'Interactif',
            },
        ],
        'excel_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Bases des Incidents',
                'desc':     'Onglet Transport généré depuis le fichier source ticketing',
                'url_name': 'platform_bases_incidents',
                'url_kwargs': {'platform': 'transmission'},
                'icon':     '📋',
                'badge':    'Excel',
            },
            {
                'num':      2,
                'title':    'Rapport 2',
                'subtitle': 'Synthèse Transport',
                'desc':     'Analyse mensuelle des incidents de transmission',
                'url_name': 'reporting_network',
                'url_kwargs': {'platform': 'transmission'},
                'icon':     '📊',
                'badge':    'Excel',
            },
        ],
        'pptx_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Comité GDI — Transport',
                'desc':     'Section Transport du rapport GDI',
                'url_name': 'generate_pptx_platform',
                'url_kwargs': {'platform': 'transmission'},
                'icon':     '🎯',
                'badge':    'PowerPoint',
            },
        ],
        'import': {
            'domains': ['transport'],
            'hint':    'Fichier brut ticketing transport',
            'accept':  '.xlsx,.xls',
        },
    },

    'igw': {
        'label':   'IGW',
        'icon':    '🔌',
        'color':   '#7c3aed',
        'color2':  '#8b5cf6',
        'domains': ['igw'],
        'tool_reports': [
            {
                'num':      1,
                'title':    'Outil 1',
                'subtitle': 'Rapport NOC CORE IP',
                'desc':     'Génération du rapport hebdomadaire ISOC CORE & IGW depuis CORE_ET_IGW_*.xlsx',
                'url_name': 'igw_rapport_noc',
                'url_kwargs': {},
                'icon':     '📋',
                'badge':    'Interactif',
            },
            {
                'num':      2,
                'title':    'Outil 2',
                'subtitle': 'Trafic International',
                'desc':     'Visualisation du trafic international par lien depuis les fichiers CSV',
                'url_name': 'igw_trafic_international',
                'url_kwargs': {},
                'icon':     '🌐',
                'badge':    'Interactif',
            },
        ],
        'excel_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Bases des Incidents',
                'desc':     'Onglet IGW généré depuis le fichier source ticketing',
                'url_name': 'platform_bases_incidents',
                'url_kwargs': {'platform': 'igw'},
                'icon':     '📋',
                'badge':    'Excel',
            },
            {
                'num':      2,
                'title':    'Rapport 2',
                'subtitle': 'Disponibilité IGW',
                'desc':     'Analyse de disponibilité de la transmission internationale',
                'url_name': 'reporting_network',
                'url_kwargs': {'platform': 'igw'},
                'icon':     '📊',
                'badge':    'Excel',
            },
        ],
        'pptx_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Comité GDI — IGW',
                'desc':     'Section IGW du rapport GDI',
                'url_name': 'generate_pptx_platform',
                'url_kwargs': {'platform': 'igw'},
                'icon':     '🎯',
                'badge':    'PowerPoint',
            },
        ],
        'import': {
            'domains': ['igw'],
            'hint':    'Fichier brut ticketing IGW',
            'accept':  '.xlsx,.xls',
        },
    },

    'core': {
        'label':   'Core Network',
        'icon':    '🌐',
        'color':   '#dc2626',
        'color2':  '#ef4444',
        'domains': ['core'],
        'excel_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Bases des Incidents',
                'desc':     'Onglet Core généré depuis le fichier source ticketing',
                'url_name': 'platform_bases_incidents',
                'url_kwargs': {'platform': 'core'},
                'icon':     '📋',
                'badge':    'Excel',
            },
            {
                'num':      2,
                'title':    'Rapport 2',
                'subtitle': 'Core Network',
                'desc':     'Analyse mensuelle des incidents core',
                'url_name': 'reporting_network',
                'url_kwargs': {'platform': 'core'},
                'icon':     '📊',
                'badge':    'Excel',
            },
        ],
        'pptx_reports': [
            {
                'num':      1,
                'title':    'Rapport 1',
                'subtitle': 'Comité GDI — Core',
                'desc':     'Section Core du rapport GDI',
                'url_name': 'generate_pptx_platform',
                'url_kwargs': {'platform': 'core'},
                'icon':     '🎯',
                'badge':    'PowerPoint',
            },
        ],
        'import': {
            'domains': ['core'],
            'hint':    'Fichier brut ticketing core',
            'accept':  '.xlsx,.xls',
        },
    },
}
