# Generated by Django 6.0.4 on 2026-04-15 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('date_rapport', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('detailed_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('synthesis_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('total_rows', models.IntegerField(default=0)),
                ('filtered_rows', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('unresolved_count', models.IntegerField(default=0)),
                ('total_duration_sec', models.FloatField(default=0)),
                ('processing_time_sec', models.FloatField(default=0)),
                ('synthesis_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
