# Generated by Django 6.0.4 on 2026-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='period_type',
            field=models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('year', 'Année')], default='day', max_length=10),
        ),
    ]
