# Generated by Django 6.0.4 on 2026-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_uploadedreport_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
