# Generated by Django 6.0.4 on 2026-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_uploadedreport_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='top_sites_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
