# Generated by Django 6.0.4 on 2026-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_uploadedreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='outage_journalier_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
