# Generated by Django 6.0.4 on 2026-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_uploadedreport_outage_journalier_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='top_causes_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
