# Generated by Django 6.0.4 on 2026-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_fix_site_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='source',
            field=models.CharField(choices=[('excel', 'Excel'), ('api', 'API')], default='excel', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
