# Generated by Django 6.0.4 on 2026-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_add_source_field_nullable_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='hauteur_pylone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='typologie_pylone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
