# Generated by Django 6.0.4 on 2026-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_site_hauteur_pylone_site_typologie_pylone'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='typologie_apres',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='typologie_avant',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
