# Generated by Django 6.0.4 on 2026-06-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_add_zone_typologie_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('mobile', 'Réseau Mobile'), ('dr2', 'DR2'), ('fixe', 'Réseau Fixe'), ('transport', 'Transport'), ('igw', 'IGW'), ('core', 'Core')], db_index=True, max_length=20)),
                ('mois_rapport', models.DateField(blank=True, db_index=True, null=True)),
                ('numero_ticket', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('nature', models.CharField(blank=True, default='', max_length=500)),
                ('alarm_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('site_parent', models.CharField(blank=True, default='', max_length=150)),
                ('site_name', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('site_id', models.CharField(blank=True, default='', max_length=30)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('base', models.CharField(blank=True, default='', max_length=50)),
                ('plateforme', models.CharField(blank=True, default='', max_length=100)),
                ('technologies', models.CharField(blank=True, default='', max_length=100)),
                ('impact_equipement', models.CharField(blank=True, default='', max_length=255)),
                ('impact_service', models.CharField(blank=True, default='', max_length=255)),
                ('escalade', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('cause', models.CharField(blank=True, default='', max_length=500)),
                ('root_cause', models.CharField(blank=True, default='', max_length=500)),
                ('action', models.CharField(blank=True, default='', max_length=500)),
                ('technicien_informe', models.CharField(blank=True, default='', max_length=200)),
                ('technicien_maint', models.CharField(blank=True, default='', max_length=200)),
                ('point_bloquant', models.CharField(blank=True, default='', max_length=500)),
                ('observation', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('nbre_clients', models.CharField(blank=True, default='', max_length=50)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-alarm_time'],
                'indexes': [models.Index(fields=['domain', 'mois_rapport'], name='reports_inc_domain_6b409c_idx'), models.Index(fields=['domain', 'escalade'], name='reports_inc_domain_1d8486_idx'), models.Index(fields=['alarm_time', 'domain'], name='reports_inc_alarm_t_bfe84e_idx')],
            },
        ),
    ]
