# Generated by Django 6.0.4 on 2026-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_add_incident_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact_equipement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact_service',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='nature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='point_bloquant',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='technicien_informe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='technicien_maint',
            field=models.TextField(blank=True, default=''),
        ),
    ]
