# Generated by Django 6.0.4 on 2026-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_incident_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='plateforme',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='incident',
            name='site_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
