# Generated by Django 6.0.4 on 2026-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_incident_wider_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_solaire_neteco',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
