# Generated by Django 6.0.4 on 2026-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_add_site_solaire_neteco'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='chef_base_dfo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='chef_base_energie',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='resp_fo_backbone_ftth',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='site_parent_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='site',
            name='site_parent_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='site',
            name='srt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='tech_energie',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='tech_field_fttx',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='tech_field_rx_mob',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='tech_fo_backbone_ftth',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
