# Generated by Django 6.0.4 on 2026-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_reassign_dr2_to_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_parent_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='site_parent_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='domain',
            field=models.CharField(choices=[('mobile', 'Réseau Mobile'), ('fixe', 'Réseau Fixe'), ('transport', 'Transport'), ('igw', 'IGW'), ('core', 'Core')], db_index=True, max_length=20),
        ),
    ]
