# Generated by Django 6.0.4 on 2026-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_site_chef_base_dfo_site_chef_base_energie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='technologie_fo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
