# Generated by Django 6.0.4 on 2026-06-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_add_site_parent_fields'),
        ('reports', '0019_alter_incident_domain'),
    ]

    operations = [
    ]
