# Generated by Django 6.0.4 on 2026-07-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_uploadedreport_transmission_stats_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_parent_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_parent_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
