# Generated by Django 6.0.4 on 2026-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_merge_0023s'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='site_duration_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
