# Generated by Django 6.0.4 on 2026-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_site_duration_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='site_top_cause_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
