# Generated by Django 6.0.4 on 2026-07-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_populate_platforms'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importcoverage',
            new_name='reports_imp_platfor_ba46de_idx',
            old_name='reports_imp_platfor_idx',
        ),
        migrations.RenameIndex(
            model_name='importcoverage',
            new_name='reports_imp_platfor_a04305_idx',
            old_name='reports_imp_status_idx',
        ),
    ]
