# Generated by Django 5.2.7 on 2026-07-12 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_rename_reports_imp_platfor_idx_reports_imp_platfor_ba46de_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('site_focus', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('question', models.TextField(blank=True, default='')),
                ('reply', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], db_index=True, default='success', max_length=10)),
                ('error_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('is_refusal', models.BooleanField(default=False)),
                ('latency_ms', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('context_chars', models.IntegerField(default=0)),
                ('history_len', models.IntegerField(default=0)),
                ('feedback', models.CharField(blank=True, choices=[('', '—'), ('up', '👍'), ('down', '👎')], db_index=True, default='', max_length=4)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('eval_success', models.BooleanField(blank=True, null=True)),
                ('eval_faithful', models.BooleanField(blank=True, null=True)),
                ('eval_hallucination', models.BooleanField(blank=True, null=True)),
                ('eval_tool_ok', models.BooleanField(blank=True, null=True)),
                ('eval_needs_human', models.BooleanField(blank=True, null=True)),
                ('eval_rating', models.IntegerField(blank=True, null=True)),
                ('eval_notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_cha_status_55c7f5_idx'), models.Index(fields=['feedback'], name='reports_cha_feedbac_ac8ee1_idx'), models.Index(fields=['site_focus'], name='reports_cha_site_fo_daffb9_idx')],
            },
        ),
    ]
