# Generated by Django 6.0.4 on 2026-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_chatinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDownAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_index=True, max_length=150)),
                ('alarm_time', models.DateTimeField(db_index=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('duration_min', models.FloatField(blank=True, null=True)),
                ('alarm_text', models.CharField(blank=True, default='', max_length=255)),
                ('cause', models.TextField(blank=True, default='')),
                ('escalade', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-alarm_time'],
                'indexes': [models.Index(fields=['alarm_time', 'site_name'], name='reports_sit_alarm_t_2f9280_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_name', 'alarm_time'), name='uniq_sitedown_site_alarmtime')],
            },
        ),
    ]
