# Generated by Django 6.0.4 on 2026-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_sitedownalarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='incidents_journaliers_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
