# Generated by Django 6.0.4 on 2026-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_uploadedreport_incidents_journaliers_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='top_causes_count_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
