# Generated by Django 6.0.4 on 2026-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_uploadedreport_cause_par_escalade_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='unresolved_sites_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
