# Generated by Django 6.0.4 on 2026-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_uploadedreport_unresolved_sites_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='unresolved_details_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
