# Generated by Django 6.0.4 on 2026-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_uploadedreport_unresolved_details_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedreport',
            name='resolved_details_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
