# Generated by Django 5.2.7 on 2026-08-06 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_uploadedreport_resolved_details_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dr2ProcessedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('sites_count', models.PositiveSmallIntegerField(default=0)),
                ('filename_2g', models.CharField(blank=True, default='', max_length=255)),
                ('filename_3g', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dr2ViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('site_name', models.CharField(db_index=True, max_length=150)),
                ('site_name_2g', models.CharField(blank=True, default='', max_length=150)),
                ('site_name_3g', models.CharField(blank=True, default='', max_length=150)),
                ('site_id', models.CharField(blank=True, default='', max_length=100)),
                ('site_parent', models.CharField(blank=True, default='', max_length=150)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('numero_ticket', models.CharField(blank=True, default='', max_length=50)),
                ('categorie', models.CharField(blank=True, default='', max_length=80)),
                ('cause', models.TextField(blank=True, default='')),
                ('point_bloquant', models.TextField(blank=True, default='')),
                ('observation', models.TextField(blank=True, default='')),
                ('alarm_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('hours_down', models.PositiveSmallIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'site_name'],
                'indexes': [models.Index(fields=['date'], name='reports_dr2_date_c1f45c_idx'), models.Index(fields=['region'], name='reports_dr2_region_de93ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'site_name'), name='uniq_dr2_date_site')],
            },
        ),
    ]
